Algoritmo "area triangulo"

//faca um algoritmo que receba a base e a altura de um triangulo,
//calcule e mostre a area do triangulo. Sabe-se que:
//area= b.h / 2

Var

base, altura, area: real


Inicio

escreva("Informe o valor da base: ")
leia(base)
escreva("Informe o valor da altura: ")
leia(altura)

area <- base * altura / 2.00

escreval("A area do triangulo = ", area)

Fimalgoritmo