Algoritmo "quadrado e cubo"
//faca um agoritmo que receba um numero positivo e maior que zero, calcule
//e mostre: o numero digitado ao quadrado e o numero digitado ao cubo

Var
num: inteiro
quadrado, cubo : real

Inicio
escreva("Informe um numero: ")
leia(num)

quadrado <- Exp(num, 2)
cubo <- Exp(num, 3)

escreval("O quadrado do numero = ", quadrado)
escreval("O cubo do numero = ", cubo)

Fimalgoritmo