Algoritmo "contar"
// contar ate 0 até o usuario quiser usando o comando enquanto

Var

   contador, numero : inteiro
   
Inicio

      escreva("Vai contar ate qual numero? ")
      leia(numero)
      
      contador <- 0
      
      enquanto (contador <= numero) faca
               escreval(contador)
               contador <- contador + 1
      fimenquanto
      
      escreval("O numero contado foi ate o: ", numero)

Fimalgoritmo